apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reference-wallet.fullname" . }}-liquidity
  labels:
    app: {{ include "reference-wallet.fullname" . }}-liquidity
    {{- include "reference-wallet.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "reference-wallet.fullname" . }}-liquidity
      {{- include "reference-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ include "reference-wallet.fullname" . }}-liquidity
        {{- include "reference-wallet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reference-wallet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - env:
        - name: FLASK_APP
          value: "app"
        - name: COMPOSE_ENV
          value: "production"
        - name: LIQUIDITY_PORT
          value: {{.Values.service.targetPort | quote}}
        - name: LP_DB_URL
          value: {{ include "reference-wallet.peripherals.database.liquidityUrl" . }}
        - name: ADMIN_USERNAME
          value: {{ .Values.peripherals.database.adminUsername }}
        {{- if .Values.custodyPrivateKeysLiquidity }}
        - name: LIQUIDITY_CUSTODY_ACCOUNT_NAME
          value: {{ .Values.custodyLiquidityAccountName | quote }}
        - name: CUSTODY_PRIVATE_KEYS
          value: {{ .Values.custodyPrivateKeysLiquidity | toJson | quote }}
        {{- end }}
        - name: ACCOUNT_WATCHER_AUTH_KEY
          value: {{ .Values.accountWatcherAuthKey | quote }}
        {{- if .Values.accountWatcherPrivKey }}
        - name: ACCOUNT_WATCHER_PRIVATE_KEY
          value: {{ .Values.accountWatcherPrivKey | quote }}
        {{- end }}
        - name: LIQUIDITY_SERVICE_PORT
          value: {{ .Values.service.targetPort | quote }}
        - name: LIQUIDITY_SERVICE_HOST
          value: {{ include "reference-wallet.fullname" . }}-liquidity
        - name: JSON_RPC_URL
          value: {{ .Values.sdk.jsonRpc }}
        - name: FAUCET_URL
          value: {{ .Values.sdk.faucet }}
        - name: CHAIN_ID
          value: {{ .Values.chainId | quote }}
        - name: BLOCKCHAIN
          value: {{ .Values.blockchain }}
        name: lrw-liquidity
        image: "{{ .Values.images.liquidity }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
          - name: http
            containerPort: {{.Values.service.targetPort}}
            protocol: TCP
