version: '3.4'
services:
  wallet-gateway:
    image: lrw_gateway
    build:
      context: ../gateway
      dockerfile: Dockerfile
      target: default_conf
    ports:
      - ${GW_PORT:-8080}:8000
    restart: always

  wallet-backend-web-server:
    image: lrw_backend
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - ../backend/.env
    environment:
      - REDIS_HOST=wallet-redis
      - COMPOSE_ENV=production
      - DB_URL=postgresql://backenduser:backendpassword@wallet-db/backend_db
      - LP_DB_URL=postgresql://backenduser:backendpassword@wallet-db/liquidity_provider_db
      - ADMIN_USERNAME=admin@lrw
    command: sh -c "/wait.sh wallet-liquidity 5000 && ./run_web.sh"
    restart: always

  wallet-backend-worker:
    image: lrw_backend
    env_file:
      - ../backend/.env
    environment:
      - REDIS_HOST=redis
      - COMPOSE_ENV=production
      - DB_URL=postgresql://backenduser:backendpassword@wallet-db/backend_db
      - LP_DB_URL=postgresql://backenduser:backendpassword@wallet-db/liquidity_provider_db
      - ADMIN_USERNAME=admin@lrw
      - PROCS=${PROCS:-2}
      - THREADS=${THREADS:-2}
    command: sh -c "/wait.sh wallet-backend-web-server 5000 && ./run_worker.sh"
    restart: always

  wallet-backend-pubsub-worker:
    image: lrw_backend
    env_file:
      - ../backend/.env
    environment:
      - REDIS_HOST=wallet-redis
      - COMPOSE_ENV=production
      - DB_URL=postgresql://backenduser:backendpassword@wallet-db/backend_db
    command: sh -c "/wait.sh wallet-backend-web-server 5000 && ./run_pubsub.sh"
    restart: always

  wallet-liquidity:
    image: lrw_liquidity
    build:
      context: ../liquidity
      dockerfile: Dockerfile
    env_file:
      - ../liquidity/.env
    environment:
      - COMPOSE_ENV=production
      - LP_DB_URL=postgresql://backenduser:backendpassword@wallet-db/liquidity_provider_db
      - ADMIN_USERNAME=admin@lrw
      - LIQUIDITY_SERVICE_HOST=wallet-liquidity
      - LIQUIDITY_SERVICE_PORT=5000
    command: sh -c "/liquidity/wait.sh wallet-db 5432 && /liquidity/run.sh"
    restart: always

  wallet-redis:
    image: redis:5
    restart: always

  wallet-db:
    image: lrw_db
    build:
      context: ./pg
    restart: always
    environment:
      - POSTGRES_PASSWORD=backenduser
      - POSTGRES_USER=backendpassword
    volumes:
      - wallet-pg-data:/var/lib/postgresql/data


volumes:
  wallet-pg-data:
    driver: local
