# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Upload to Testflight"
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "LRW.xcodeproj")
      ) + 1,
    )
    match(type: "appstore")
    gym(scheme: "LRW", xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{ENV['PROVISIONING_PROFILE']}'")
    pilot(
      distribute_external: true,
      notify_external_testers: false,
      changelog: "CircleCI build"
    )
  end
end
