
# Address of the wallet VASP account. This value cannot be empty
vaspAddr:
# Private key of the wallet VASP account. This value cannot be empty
vaspPrivateKey:
# Wallet VASP compliance private key. This value cannot be empty
vaspComplianceKey:

# Host name of the liquidity provider service
liquidityProviderHost: liquidity-emulator
liquidityProviderPort: 8080

custodyWalletAccountName: wallet1

walletAdminUsername: "admin@diem"

gasCurrencyCode: "XUS"

# Diem chain ID. Should be modified if deploying not for testnet
chainId: 2

sdk:
  # Diem JSON-RPC API URL. Should be modified if deploying not for testnet
  jsonRpc: "https://testnet.diem.com/v1"
  faucet: "http://testnet.diem.com/mint"

images:
  pullPolicy: Never
  backend: lrw_backend
  frontend: lrw_gateway

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
apiPath: "/api"

workers:
  numProcs: 2
  numThreads: 2

peripherals:
  redis:
    # Should a database service be created?
    # If false, host:port should point to an existing DB instance
    create: false
    image: "redis:5"
    # if redis is created by this helm chart, there is no need to fill the following
    host: ""
    port: 6379
    persistence: {}

  database:
    # Should a database service be created?
    # If false, host:port should point to an existing DB instance
    create: false
    image: "lrw_db"
    # if database is created by this helm chart, there is no need to fill the following
    protocol: "postgresql"
    username: "backenduser"
    password: "backendpassword"
    host:
    port: 5432
    dbName: "backend_db"
    persistence: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  host: lrw.demo
  annotations: {}

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
